#!/usr/bin/env bash
# Auto-fix and re-stage changes.

staged_files=$(git diff --cached --name-only --diff-filter=ACM)
[ -z "$staged_files" ] && exit 0

lint_files=$(echo "$staged_files" | grep -E '\.(ts|tsx|astro)$')
if [ -n "$lint_files" ]; then
  pnpm exec eslint --fix $lint_files
fi

format_files=$(echo "$staged_files" | grep -E '\.(ts|tsx|astro|css|json|md|mdx)$')
if [ -n "$format_files" ]; then
  pnpm exec prettier --write $format_files
fi

echo "$staged_files" | xargs git add

exit 0
